# Theme
remote_theme: pmarsceill/just-the-docs
color_scheme: 'nitrado_js'

# Logo image
logo: '/assets/img/package-logo.png'

# Aux link in top right of page
aux_links:
    'Nitrado.js on GitHub':
        - 'https://github.com/cainthebest/nitrado.js'
# Aux link will open a new tab
aux_links_new_tab: true

# Base URL
url: "https://docs.nitradojs.xyz"
